/* Conteúdo novo da edição 2 (Atlas, Apostila e aprofundamento). Formato: {c, q, o:[certa, ...erradas], e} */
var NOVAS_Q=[
// posição
{c:'posicao',q:'Na cabeça, o termo para “em direção ao focinho” é:',o:['Rostral','Cranial','Dorsal','Proximal'],e:'A cabeça já é o extremo cranial do corpo; dentro dela usa-se rostral (focinho) e caudal.'},
{c:'posicao',q:'O plano que divide o animal em antímeros direito e esquerdo é o:',o:['Sagital mediano','Dorsal','Transversal','Sagital paramediano'],e:'Planos sagitais paralelos a ele não dividem em metades iguais.'},
{c:'posicao',q:'A face de trás do metatarso é chamada de:',o:['Plantar','Palmar','Caudal','Ventral'],e:'Palmar é só no membro torácico (do carpo para baixo).'},
{c:'posicao',q:'Do carpo para baixo, a face da frente do membro é chamada de:',o:['Dorsal','Cranial','Rostral','Ventral'],e:'Acima do carpo/tarso usa-se cranial e caudal; abaixo, dorsal e palmar/plantar.'},
{c:'posicao',q:'Em ruminantes, a face do dedo voltada para o eixo entre o 3º e o 4º dedos é a face:',o:['Axial','Abaxial','Medial','Palmar'],e:'A face oposta, voltada para fora, é a abaxial.'},
{c:'posicao',q:'Os termos “superior” e “inferior” são usados em anatomia veterinária apenas para:',o:['Lábios e pálpebras','Membros','Vértebras','Tronco'],e:'No resto do corpo usam-se dorsal, ventral, cranial, caudal.'},
{c:'posicao',q:'O plano paralelo ao dorso, que separa uma parte dorsal de uma ventral, é o plano:',o:['Dorsal (frontal)','Sagital','Transversal','Mediano'],e:'O transversal corta perpendicularmente ao eixo longo, “em fatias”.'},
{c:'posicao',q:'No membro, a estrutura mais próxima do tronco é:',o:['Proximal','Distal','Medial','Rostral'],e:'Distal é a mais afastada, em direção ao casco ou à unha.'},
{c:'posicao',q:'Na posição anatômica, o quadrúpede está:',o:['Em estação, com os quatro membros apoiados e a cabeça erguida','Deitado em decúbito dorsal','Em decúbito lateral','Sentado sobre os membros pélvicos'],e:'Posição de alerta: membros estendidos, pescoço erguido, olhar no horizonte.'},
{c:'posicao',q:'“Medial” significa:',o:['Mais perto do plano mediano','Mais longe do plano mediano','Em direção ao dorso','Em direção à cauda'],e:'Lateral é o oposto: mais longe do plano mediano.'},
// esqueleto
{c:'esqueleto',q:'Costelas e fíbula são longas, mas sem cavidade medular. Elas são ossos:',o:['Alongados','Longos','Planos','Irregulares'],e:'Classificação da apostila: alongados são longos e achatados, sem canal medular.'},
{c:'esqueleto',q:'Ossos com cavidades cheias de ar, revestidas por mucosa, são chamados:',o:['Pneumáticos','Sesamoides','Alongados','Curtos'],e:'Ex.: frontal, maxila, esfenoide, etmoide, temporal e palatino (seios paranasais).'},
{c:'esqueleto',q:'A patela é um exemplo de osso:',o:['Sesamoide','Curto','Plano','Irregular'],e:'Sesamoides ficam dentro de tendões e funcionam como roldana.'},
{c:'esqueleto',q:'Segundo a apostila, qual destas espécies tem mais ossos?',o:['Suíno (223)','Bovino (188)','Equino (189)','Humano (206)'],e:'Cão tem 215. O número varia com a idade e com o critério de contagem.'},
{c:'esqueleto',q:'Como o membro torácico se prende ao tronco?',o:['Só por músculos, sem articulação óssea','Por uma articulação sinovial com as costelas','Pela clavícula, em todas as espécies','Por uma sínfise com o esterno'],e:'A escápula fica presa por músculos (sinsarcose); o pélvico se prende ao sacro por osso.'},
{c:'esqueleto',q:'Tubérculo, tuberosidade e trocânter são saliências que servem para:',o:['Inserção de tendões e ligamentos','Articulação com outro osso','Passagem de vasos','Alojar a medula óssea'],e:'Côndilo, cabeça e tróclea é que são saliências articulares.'},
{c:'esqueleto',q:'São exemplos de ossos longo, plano, curto e irregular, nesta ordem:',o:['Fêmur, escápula, carpo, vértebra','Escápula, fêmur, carpo, vértebra','Vértebra, fêmur, escápula, carpo','Carpo, vértebra, fêmur, escápula'],e:'Questão da apostila: longo = fêmur; plano = escápula; curto = carpos; irregular = vértebras.'},
{c:'esqueleto',q:'Sobre os ossos longos, é INCORRETO afirmar:',o:['Apenas os ossos longos possuem medula óssea','Comprimento maior que largura e espessura','Úmero, rádio, fêmur e tíbia são exemplos','Possuem osso compacto e esponjoso'],e:'Ossos curtos, planos e irregulares também têm medula no osso esponjoso.'},
// ósseo
{c:'osseo',q:'Na remodelação, a fase em que os osteoclastos saem e os osteoblastos chegam à cavidade é a:',o:['Reversão','Reabsorção','Formação','Repouso'],e:'Repouso → reabsorção → reversão → formação.'},
{c:'osseo',q:'O primeiro evento da ossificação endocondral no molde de cartilagem é:',o:['Condrócitos do centro hipertrofiam e a cartilagem calcifica','Surgem os centros secundários nas epífises','Forma-se a linha epifisária','Aparece a medula amarela'],e:'Logo depois forma-se o colar ósseo e os vasos invadem (centro primário).'},
{c:'osseo',q:'Os centros secundários de ossificação aparecem nas:',o:['Epífises','Diáfises','Cavidades medulares','Membranas sinoviais'],e:'O centro primário é diafisário.'},
{c:'osseo',q:'Na radiografia de um filhote, uma faixa escura entre epífise e diáfise geralmente é:',o:['O disco epifisário, normal','Uma fratura','Osteoporose','Um canal de Havers'],e:'Conhecer a anatomia evita confundir o disco de crescimento com fratura.'},
{c:'osseo',q:'Quando o crescimento termina, o disco epifisário se transforma em:',o:['Linha epifisária','Cartilagem articular','Canal medular','Periósteo'],e:'A cartilagem é substituída por osso e sobra só uma linha.'},
{c:'osseo',q:'O osteoide é:',o:['Matriz óssea recém-formada, ainda não mineralizada','Matriz já calcificada','Uma célula gigante','O tecido da medula amarela'],e:'Fica entre os osteoblastos e a matriz mineralizada.'},
// tireoide
{c:'tireoide',q:'Quando o cálcio do sangue cai, qual célula óssea aumenta sua atividade?',o:['Osteoclasto','Osteoblasto','Célula parafolicular','Condrócito'],e:'O PTH estimula a reabsorção para liberar cálcio da matriz.'},
{c:'tireoide',q:'Os hormônios T3 e T4 são produzidos pelas:',o:['Células foliculares da tireoide','Células parafoliculares','Células principais da paratireoide','Células do coloide'],e:'Ficam armazenados no coloide.'},
{c:'tireoide',q:'A calcitonina reduz o cálcio sanguíneo principalmente:',o:['Inibindo os osteoclastos','Estimulando os osteoclastos','Aumentando o PTH','Dissolvendo o coloide'],e:'Com menos reabsorção, o cálcio fica guardado no osso.'},
// cartilagem
{c:'cartilagem',q:'A cartilagem da epiglote é:',o:['Elástica','Hialina','Fibrosa','Calcificada'],e:'Também o pavilhão auricular e a tuba auditiva.'},
{c:'cartilagem',q:'Os meniscos do joelho são formados por cartilagem:',o:['Fibrosa','Hialina','Elástica','Articular'],e:'Fibrocartilagem aguenta pressão e tração.'},
{c:'cartilagem',q:'A cartilagem articular é hialina, mas NÃO tem:',o:['Pericôndrio','Condrócitos','Colágeno tipo II','Matriz extracelular'],e:'Ela se nutre pelo líquido sinovial.'},
{c:'cartilagem',q:'A matriz territorial é:',o:['A faixa mais basófila em volta do grupo isógeno','A camada fibrosa do pericôndrio','O espaço entre dois ossos','A cavidade articular'],e:'A interterritorial é a matriz mais clara entre os grupos.'},
// articulações
{c:'articulacoes',q:'Diminuir o ângulo entre dois ossos é:',o:['Flexão','Extensão','Abdução','Rotação'],e:'Extensão aumenta o ângulo.'},
{c:'articulacoes',q:'A articulação atlanto-occipital faz o movimento do:',o:['“Sim” (flexão e extensão da cabeça)','“Não” (rotação)','Circundução','Deslizamento lateral'],e:'O “não” é da atlantoaxial (trocóide).'},
{c:'articulacoes',q:'A união entre rádio e ulna por ligamento interósseo é uma:',o:['Sindesmose','Sutura','Gonfose','Sincondrose'],e:'Ossos à distância unidos por ligamento ou membrana.'},
{c:'articulacoes',q:'As articulações entre os ossos do carpo são do tipo:',o:['Plana (artródia)','Gínglimo','Trocóide','Esferóide'],e:'Superfícies planas que deslizam.'},
{c:'articulacoes',q:'A camada externa da cápsula articular é formada por:',o:['Tecido fibroso','Membrana sinovial','Cartilagem hialina','Tecido adiposo'],e:'A interna é a membrana sinovial, que produz o líquido.'},
// crânio
{c:'cranio',q:'Crânio com processo cornual e sem dentes incisivos superiores é de:',o:['Bovino','Equino','Cão','Suíno'],e:'No lugar dos incisivos superiores há o pulvino dental.'},
{c:'cranio',q:'Órbita “aberta”, fechada atrás só por um ligamento, é típica do:',o:['Cão','Equino','Bovino','Ovino'],e:'Nos herbívoros a órbita é fechada por osso.'},
{c:'cranio',q:'Nos herbívoros, o que fecha a órbita por trás é o:',o:['Processo zigomático do frontal','Processo coronoide','Processo jugular','Processo cornual'],e:'Ele desce até encontrar o arco zigomático.'},
{c:'cranio',q:'A sutura entre os dois ossos frontais é a:',o:['Interfrontal','Internasal','Coronal','Frontolacrimal'],e:'É do tipo serrada.'},
{c:'cranio',q:'A sutura coronal une:',o:['Frontal e parietal','Nasal e frontal','Os dois parietais','Occipital e parietal'],e:'Também chamada frontoparietal.'},
{c:'cranio',q:'Na descorna de um bovino adulto, pode ser exposto o:',o:['Seio frontal','Seio maxilar','Meato nasal ventral','Forame magno'],e:'O seio frontal se estende para dentro do processo cornual.'},
{c:'cranio',q:'No equino, as raízes dos últimos molares superiores ficam dentro do:',o:['Seio maxilar','Seio frontal','Canal interincisivo','Meato acústico'],e:'Por isso infecção dentária vira sinusite.'},
{c:'cranio',q:'O forame mandibular fica:',o:['Na face medial do ramo da mandíbula','Na face lateral do corpo','No processo coronoide','Na sínfise'],e:'O mentual (mentoniano) é que fica na face lateral do corpo.'},
{c:'cranio',q:'No equino, o pulso é aferido na artéria facial, na:',o:['Incisura dos vasos faciais da mandíbula','Fossa temporal','Crista facial','Bula timpânica'],e:'Na borda ventral do corpo da mandíbula.'},
{c:'cranio',q:'A sínfise mandibular se ossifica cedo, formando peça única, no:',o:['Equino e suíno','Cão e gato','Bovino e ovino','Gato e bovino'],e:'Em carnívoros e ruminantes ela fica fibrocartilaginosa.'},
{c:'cranio',q:'O processo lingual pertence ao:',o:['Basi-hioide','Estilo-hioide','Epi-hioide','Temporal'],e:'Presente em equino e bovino; entra na raiz da língua.'},
{c:'cranio',q:'O osso que forma o teto da cavidade nasal é o:',o:['Nasal','Vômer','Etmoide','Palatino'],e:'O vômer forma a parte ventral do septo.'},
{c:'cranio',q:'O canal interincisivo pertence ao osso:',o:['Incisivo','Maxilar','Palatino','Nasal'],e:'Visto na face ventral, atrás dos dentes incisivos.'},
{c:'cranio',q:'O processo coronoide da mandíbula serve para:',o:['Inserção do músculo temporal','Articular com o temporal','Passagem do nervo alveolar','Alojar os molares'],e:'Quem articula é o processo condilar.'},
{c:'cranio',q:'O aparelho hioide é classificado como esqueleto:',o:['Visceral','Axial','Apendicular','Cíngulo'],e:'Não se articula com o esqueleto do tronco.'},
// coluna
{c:'coluna',q:'O atlas dos ruminantes NÃO tem:',o:['Forame transverso','Forame alar','Forame vertebral lateral','Asas'],e:'O processo transverso típico está ausente.'},
{c:'coluna',q:'No cão, no lugar do forame alar do atlas existe a:',o:['Incisura alar','Fóvea do dente','Fossa do atlas','Crista ventral'],e:'Um entalhe aberto na borda da asa.'},
{c:'coluna',q:'O forame intervertebral é formado por:',o:['Incisuras vertebrais de duas vértebras vizinhas','O forame transverso','O canal sacral','O espaço interarcual'],e:'Por ele sai o nervo espinhal.'},
{c:'coluna',q:'O processo mamilar aparece nas vértebras:',o:['Torácicas caudais e lombares','Cervicais','Sacrais','Caudais finais'],e:'Fica sobre o processo articular cranial.'},
{c:'coluna',q:'A 7ª vértebra cervical geralmente:',o:['Não tem forame transverso e tem fóvea costal caudal','Tem dente','Tem forame alar','Não tem processo espinhoso'],e:'A fóvea recebe a cabeça da 1ª costela.'},
{c:'coluna',q:'No cão, a vértebra anticlinal (processo espinhoso vertical) costuma ser a:',o:['T11','C7','L1','T1'],e:'Referência na radiografia da coluna.'},
{c:'coluna',q:'A crista sacral mediana é formada pela fusão dos:',o:['Processos espinhosos','Processos transversos','Processos articulares','Corpos vertebrais'],e:'Intermédia = articulares; lateral = transversos.'},
{c:'coluna',q:'Processos hemais aparecem nas:',o:['Primeiras vértebras caudais de ruminantes e carnívoros','Cervicais do equino','Lombares do suíno','Torácicas do cão'],e:'Protegem os vasos coccígeos medianos.'},
{c:'coluna',q:'A anestesia epidural no cão é feita no espaço:',o:['Lombossacro','Atlanto-occipital','Entre T13 e L1','Intercostal'],e:'Espaço interarcual entre L7 e o sacro.'},
{c:'coluna',q:'Costelas asternais são as que:',o:['Unem sua cartilagem à da costela anterior, formando o arco costal','Se articulam diretamente com o esterno','Não têm cartilagem','Se articulam com o sacro'],e:'As esternais tocam o esterno; as flutuantes não se ligam a nada.'},
{c:'coluna',q:'O equino tem quantos pares de costelas esternais?',o:['8','10','13','18'],e:'18 pares no total: 8 esternais e 10 asternais.'},
{c:'coluna',q:'O sulco costal fica:',o:['Na borda caudal do corpo da costela','Na cabeça da costela','No tubérculo','Na cartilagem costal'],e:'Por ele passam os vasos e nervos intercostais.'},
{c:'coluna',q:'Articulações sinoviais entre os processos transversos das últimas lombares são exclusivas do:',o:['Equino','Cão','Bovino','Suíno'],e:'Articulações intertransversais, também com a asa do sacro.'},
{c:'coluna',q:'O atlas se articula cranialmente com:',o:['Os côndilos do occipital','O dente do áxis','A bula timpânica','O processo jugular'],e:'Caudalmente, com o áxis.'},
{c:'coluna',q:'O cão tem quantas esternébras?',o:['8','5','7','13'],e:'Cilíndricas, unidas por cartilagem.'},
// torácico
{c:'toracico',q:'O acrômio está AUSENTE em:',o:['Equino e suíno','Cão e gato','Bovino e ovino','Gato e bovino'],e:'Acrômio só em carnívoros e ruminantes.'},
{c:'toracico',q:'O processo supra-hamato da escápula é característico do:',o:['Gato','Cão','Equino','Bovino'],e:'O cão tem só o processo hamato.'},
{c:'toracico',q:'O forame supratroclear do úmero é característico do:',o:['Cão','Equino','Bovino','Suíno'],e:'Comunica a fossa radial com a fossa do olécrano.'},
{c:'toracico',q:'Na fileira distal do carpo do bovino há:',o:['Cárpicos II+III fundidos e IV','Cárpicos I, II, III e IV separados','Intermediorradial e ulnar','Apenas o cárpico III'],e:'Total de 6 ossos no carpo bovino.'},
{c:'toracico',q:'Os “ossos esplintes” do cavalo são:',o:['Os metacárpicos II e IV rudimentares','Os sesamoides proximais','A falange média','O carpo acessório'],e:'Ficam ao lado do metacárpico III, sem dedo.'},
{c:'toracico',q:'O nome popular da falange média do equino é:',o:['Coroa','Quartela','Casco','Canela'],e:'Quartela = proximal; casco = distal; canela = metacarpo III.'},
{c:'toracico',q:'O sesamoide distal do equino é chamado de:',o:['Osso navicular','Fabela','Patela','Osso esplinte'],e:'Fica na face palmar, entre a falange média e a distal.'},
{c:'toracico',q:'A tuberosidade flexora é estrutura da:',o:['Falange média','Falange distal','Escápula','Ulna'],e:'Na face palmar da falange média.'},
{c:'toracico',q:'O antebraço do bovino tem quantos espaços interósseos?',o:['Dois (proximal e distal)','Um','Nenhum','Três'],e:'Rádio e ulna se fundem no meio.'},
{c:'toracico',q:'No metacarpo do bovino, os sulcos longitudinais dorsal e palmar indicam:',o:['A fusão dos metacárpicos III e IV','A passagem do nervo radial','O limite do carpo','Um osso rudimentar V'],e:'O osso único nasceu de dois.'},
{c:'toracico',q:'A face serrátil da escápula fica na face:',o:['Medial (costal)','Lateral','Distal','Cranial'],e:'Prende o músculo serrátil ventral.'},
{c:'toracico',q:'O carpo do equino tem:',o:['7 a 8 ossos','5 ossos','6 ossos','10 ossos'],e:'O cárpico I é inconstante.'},
{c:'toracico',q:'O tubérculo supraglenoidal aponta para qual direção?',o:['Cranial','Caudal','Dorsal','Medial'],e:'Origem do músculo bíceps braquial; ajuda a dizer o lado da escápula.'},
// pélvico
{c:'pelvico',q:'Os três ossos do coxal se fundem no:',o:['Acetábulo','Forame obturado','Arco isquiático','Promontório'],e:'Cada um tem seu centro de ossificação.'},
{c:'pelvico',q:'A tuberosidade isquiática “trituberosa” é típica do:',o:['Bovino','Equino','Cão','Gato'],e:'Três saliências na ponta da nádega.'},
{c:'pelvico',q:'O diâmetro conjugado da pelve vai do:',o:['Promontório sacral à borda cranial da sínfise púbica','Acetábulo direito ao esquerdo','Arco isquiático ao sacro','Ílio ao fêmur'],e:'Importante na avaliação obstétrica.'},
{c:'pelvico',q:'Fabelas são sesamoides encontrados:',o:['Atrás dos côndilos do fêmur de cães e gatos','No tendão do bíceps do equino','No casco do bovino','Na ATM'],e:'Ficam dentro do músculo gastrocnêmio.'},
{c:'pelvico',q:'O tarso do equino tem:',o:['6 ossos (I e II fundidos)','5 ossos','7 ossos','8 ossos'],e:'Tálus, calcâneo, central, I+II, III, IV.'},
{c:'pelvico',q:'O osso centroquartal é a fusão do tarso central com o tarsal IV e existe no:',o:['Bovino','Equino','Cão','Suíno'],e:'O bovino tem 5 ossos no tarso.'},
{c:'pelvico',q:'O tálus com duas trócleas (proximal e distal) identifica:',o:['Ruminantes','Equino','Cão','Gato'],e:'Movimento extra no jarrete do boi.'},
{c:'pelvico',q:'O osso maleolar dos ruminantes corresponde à:',o:['Extremidade distal da fíbula','Patela','Cabeça do fêmur','Tuberosidade do calcâneo'],e:'Faz o papel do maléolo lateral.'},
{c:'pelvico',q:'A fossa trocantérica do fêmur fica na face:',o:['Caudal','Cranial','Lateral','Medial'],e:'Entre o trocânter maior e o colo.'},
{c:'pelvico',q:'Na patela, a parte proximal é a __ e a distal é o __.',o:['base; ápice','ápice; base','cabeça; colo','côndilo; tróclea'],e:'Base em cima, ápice embaixo.'},
{c:'pelvico',q:'Na tuberosidade do calcâneo se insere o:',o:['Tendão calcâneo comum','Ligamento patelar','Ligamento cruzado','Músculo glúteo'],e:'É a “ponta do jarrete”.'},
{c:'pelvico',q:'O pecten é uma estrutura do:',o:['Púbis','Ílio','Ísquio','Sacro'],e:'Borda cranial do púbis.'},
{c:'pelvico',q:'A face auricular do ílio se articula com:',o:['O sacro','O fêmur','A última costela','O púbis do outro lado'],e:'Articulação sacroilíaca.'},
// espécies
{c:'especies',q:'Um fêmur com terceiro trocânter evidente é de:',o:['Equino','Bovino','Cão','Suíno'],e:'Marca registrada do cavalo.'},
{c:'especies',q:'Um metacarpo único formado por dois ossos fundidos, com sulco no meio, é de:',o:['Bovino','Equino','Cão','Suíno'],e:'Ruminantes fundem III e IV.'},
{c:'especies',q:'Escápula com acrômio e processo hamato, sem túber da espinha, é de:',o:['Cão','Equino','Suíno','Bovino'],e:'O gato também tem o supra-hamato.'},
{c:'especies',q:'Ulna que termina no meio do rádio, fundida a ele, é de:',o:['Equino','Bovino','Cão','Suíno'],e:'Nas outras espécies a ulna é completa.'},
{c:'especies',q:'Qual destes animais tem a fíbula completa?',o:['Cão','Equino','Bovino','Ovino'],e:'Também gato e suíno.'},
{c:'especies',q:'18 pares de costelas indicam:',o:['Equino','Bovino','Cão','Suíno'],e:'18 torácicas.'},
{c:'especies',q:'Carpo com 8 ossos (4 em cada fileira) é de:',o:['Suíno','Cão','Bovino','Equino'],e:'Cão tem 7, bovino 6, equino 7–8.'},
{c:'especies',q:'Úmero com tubérculo intermédio e dois sulcos intertuberculares é de:',o:['Equino','Bovino','Cão','Gato'],e:'Exclusivo do cavalo.'},
{c:'especies',q:'Atlas sem forame transverso é de:',o:['Bovino','Equino','Cão','Gato'],e:'Ruminantes não têm o forame transverso no atlas.'},
{c:'especies',q:'O osso rostral, no focinho, é encontrado no:',o:['Suíno','Equino','Cão','Bovino'],e:'Esqueleto visceral; ajuda a fuçar.'},
{c:'especies',q:'O cão é um animal:',o:['Digitígrado','Ungulígrado','Plantígrado','Ungulado'],e:'Apoia os dedos inteiros no chão.'},
{c:'especies',q:'Um sacro com 3 vértebras fundidas indica:',o:['Cão ou gato','Equino','Bovino','Suíno'],e:'Equino e bovino: 5; suíno: 4.'},
{c:'especies',q:'Escápula sem acrômio e com túber da espinha enorme, curvado caudalmente, é de:',o:['Suíno','Equino','Cão','Bovino'],e:'O equino também não tem acrômio, mas o túber é menor e a cartilagem é grande.'},
{c:'especies',q:'Animais ungulados são os que:',o:['Caminham sobre dígitos revestidos por casco','Caminham sobre toda a planta do pé','Têm cinco dedos apoiados','Não têm falanges'],e:'Questão da apostila: cão e gato não são ungulados.'}
];
var NOVOS_FC=[
['posicao','Rostral × cranial','Rostral só na cabeça (em direção ao focinho); cranial no tronco e pescoço.'],
['posicao','Dorsal × palmar × plantar','Do carpo/tarso para baixo: frente = dorsal; trás = palmar (torácico) ou plantar (pélvico).'],
['posicao','Axial × abaxial','Dedos de ruminantes e suínos: axial = voltada para o eixo entre o 3º e o 4º dedo; abaxial = oposta.'],
['posicao','Os 4 planos','Sagital mediano, sagital, dorsal (frontal) e transversal.'],
['posicao','Os 3 eixos','Longitudinal (craniocaudal), sagital (dorsoventral) e laterolateral.'],
['esqueleto','Ossos alongados','Longos e achatados, sem canal medular: costelas, fíbula.'],
['esqueleto','Ossos pneumáticos','Com seios de ar: frontal, maxila, esfenoide, etmoide, temporal, palatino.'],
['esqueleto','Ossos sesamoides','Dentro de tendões, funcionam como roldana: patela, navicular, sesamoides proximais, fabelas.'],
['osseo','Fases da remodelação','Repouso → reabsorção (osteoclasto) → reversão → formação (osteoblasto).'],
['osseo','Centros de ossificação','Primário na diáfise; secundários nas epífises. Disco epifisário entre eles.'],
['tireoide','Cálcio baixo no sangue','Paratireoide libera PTH → osteoclastos reabsorvem → Ca sai do osso para o sangue.'],
['tireoide','Cálcio alto no sangue','Células C da tireoide liberam calcitonina → inibe osteoclastos → Ca fica no osso.'],
['cranio','Órbita fechada × aberta','Fechada por osso (processo zigomático do frontal) no equino e bovino; aberta (ligamento orbital) no cão, gato e suíno.'],
['cranio','Marcas do crânio bovino','Frontal gigante, processo cornual, crista intercornual, sem incisivos superiores.'],
['cranio','Marcas do crânio equino','Face longa, crista facial, forame infraorbitário, órbita fechada, processo jugular longo.'],
['cranio','Sutura coronal','Entre frontal e parietal (frontoparietal).'],
['cranio','Seios mais cobrados','Frontal (bovino: entra no corno) e maxilar (equino: raízes dos molares).'],
['cranio','Partes do hioide','Estilo-, epi-, cerato-, basi- e tíreo-hioide (+ timpano-hioide cartilaginoso).'],
['cranio','Sínfise mandibular','Ossifica no equino e suíno; fica fibrocartilaginosa no cão, gato e ruminantes.'],
['coluna','Os 3 forames do atlas','Vertebral lateral (arco dorsal), alar (cranial) e transverso (caudal).'],
['coluna','Atlas: ruminante × cão','Ruminante sem forame transverso; cão com incisura alar no lugar do forame alar.'],
['coluna','C7','Mais curta e larga; sem forame transverso; fóvea costal caudal para a 1ª costela.'],
['coluna','Cristas do sacro','Mediana (espinhosos), intermédia (articulares), lateral (transversos).'],
['coluna','Costelas: esternais, asternais, flutuantes','Tocam o esterno; unem-se à cartilagem anterior (arco costal); soltas.'],
['coluna','Partes da costela','Cabeça, colo, tubérculo, ângulo, corpo (sulco costal), cartilagem costal.'],
['toracico','Acrômio por espécie','Presente em carnívoros e ruminantes; ausente no equino e suíno.'],
['toracico','Carpo do bovino','Proximal: radial, intermédio, ulnar, acessório. Distal: II+III, IV. Total 6.'],
['toracico','Falange distal do equino','Face parietal, face solear, processo extensor, processos palmares, margem coronária, cartilagens ungulares.'],
['toracico','Nomes populares do dedo equino','Canela, boleto, quartela, coroa, casco (navicular).'],
['toracico','Úmero: cão × gato','Cão: forame supratroclear. Gato: forame supracondilar (medial).'],
['pelvico','Tarso por espécie','Equino 6 (I+II); bovino 5 (centroquartal, II+III); cão e suíno 7.'],
['pelvico','Diâmetros da pelve','Conjugado (promontório → sínfise), transverso, vertical.'],
['pelvico','Fíbula por espécie','Equino: incompleta, maléolo fundido à tíbia. Ruminante: cabeça fundida + osso maleolar. Cão, gato, suíno: completa.'],
['pelvico','Patela','Base proximal, ápice distal; sesamoide no tendão do quadríceps; desliza na tróclea.'],
['especies','5 perguntas de identificação','Terceiro trocânter? Metacarpo fundido? Escápula sem acrômio? Ulna até o meio? Fíbula completa?']
];
